; 官方文檔：https://developers.line.biz/en/reference/messaging-api/
[Channel]
; 請在雙引號內輸入您的 Line Bot "Channel access token"
Token = "EUKR6t0dVL+9xSyFMd40eUncTrJfei5VqI3eHmdEx4pPdmamjlGBF9KzJlGRSB1MY7duqZP84gcrhjR2qhfS+i3L1QvLfo3UjwRDG2sd1ChXgwmvIg7M+mhRwy6Crzs19VLc8CoEnMnRDWDfUSTW8gdB04t89/1O/w1cDnyilFU="
; 請在雙引號內輸入您的 Line Bot "Channel secret"
Secret = "2a6b3382616ec84cbaa913dbdfb340f3"